/* ///////////////////////////////////////////////////////////////////// */
/*!
 
                                                                                                                                                                                                                             \f]
                                                                                                                                                                                                                               while the remaining vector components are 0.
                                                                                                                                                                                                                                 The cloud has radius \f$R\f$ centered at
                                                                                                                                                                                                                                   \f$r_0 = (x_0,y_0,z_0) = (0.8, 0.5, 0.5)\f$ and larger density 
                                                                                                                                                                                                                                     \f$\rho = 10\f$.
                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                       The interaction may be divided into two phases: 1) the collapse stage
                                                                                                                                                                                                                                         where the front of the cloud is strongly compressed and two fast shocks
                                                                                                                                                                                                                                           are generated and 2) the reexpansion phase which begins when the 
                                                                                                                                                                                                                                             transmitted fast shock overtake the back of the cloud.
                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                 The runtime parameters that are read from \c pluto.ini are 
                                                                                                                                                                                                                                                   - <tt>g_inputParam[B_POST]</tt>: sets the post-shock magnetic field;
                                                                                                                                                                                                                                                     - <tt>g_inputParam[B_PRE]</tt>:  sets the pre-shock magnetic field;
                                                                                                                                                                                                                                                       - <tt>g_inputParam[RADIUS]</tt>: sets the radius of the cloud;
                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                         A list of the available configurations is given in the following table:
                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                           <CENTER>
                                                                                                                                                                                                                                                             Conf.| GEOMETRY  |DIM| T. STEPPING|RECONSTRUCTION|divB|  AMR
                                                                                                                                                                                                                                                               -----|-----------|---|------------|--------------| ---|-------
                                                                                                                                                                                                                                                                  #01 |CARTESIAN  | 2 |  RK2       |  LINEAR      | CT | NO
                                                                                                                                                                                                                                                                     #02 |CARTESIAN  | 2 |  ChTr      |  LINEAR      | CT | NO    
                                                                                                                                                                                                                                                                        #03 |CARTESIAN  | 2 |  HANCOCK   |  LINEAR      | 8W | NO    
                                                                                                                                                                                                                                                                           #04 |CARTESIAN  | 3 |  ChTr      |  LINEAR      | CT | NO
                                                                                                                                                                                                                                                                              #05 |CARTESIAN  | 3 |  RK3       |  LINEAR      | CT | NO    
                                                                                                                                                                                                                                                                                 #06 |CARTESIAN  | 3 | ChTr       |  LINEAR      | GLM| NO    
                                                                                                                                                                                                                                                                                    #07 |CARTESIAN  | 3 |  RK3       |  WENO3_FD    | GLM| NO    
                                                                                                                                                                                                                                                                                       #08 |CARTESIAN  | 3 | HANCOK     |  LINEAR      | GLM| YES
                                                                                                                                                                                                                                                                                          #09 |CARTESIAN  | 2 |  RK2       |  LINEAR      | CT | NO 
                                                                                                                                                                                                                                                                                            </CENTER>
                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                              \image html mhd_shock_cloud.02.jpg "Density map with overplotted field lines for configuration #02"
                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                \author A. Mignone (mignone@ph.unito.it)
                                                                                                                                                                                                                                                                                                  \date   Sept 17, 2014
                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                    \b References:
                                                                                                                                                                                                                                                                                                         - "Interactions between magnetohydrodynamical shocks and denser clouds"
                                                                                                                                                                                                                                                                                                                 W. Dai an P.R. Woodward, ApJ (1994) 436, 776.
                                                                                                                                                                                                                                                                                                                      - "The divB = 0 Constraint in Shock-Capturing MHD codes"
                                                                                                                                                                                                                                                                                                                              G. Toth, JCP 161, 605-652 (2000)
                                                                                                                                                                                                                                                                                                                                   - "A central constrained transport scheme for ideal magnetohydrodynamics" 
                                                                                                                                                                                                                                                                                                                                           U. Ziegler, JCP 196 (2004), 393
                                                                                                                                                                                                                                                                                                                                           */
                                                                                                                                                                                                                                                                                                                                           /* ///////////////////////////////////////////////////////////////////// */
#include <stdio.h>
//#include <iostream>
//#include <math.h>                                                                                                                                                                                                                                                                                                                                         

#include "pluto.h"
                                                                                                                                                                                                                                                                                                                                           
//#define max(A,B) ((A)>(B) ? (A) : (B))
//#define min(A,B) ((A)<(B) ? (A) : (B))                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                           /* ********************************************************************* */
                                                                                                                                                                                                                                                                                                                                           void Init (double *v, double x, double y, double z)
                                                                                                                                                                                                                                                                                                                                           /*
                                                                                                                                                                                                                                                                                                                                            *
                                                                                                                                                                                                                                                                                                                                             *********************************************************************** */
                                                                                                                                                                                                                                                                                                                                             {
                                                                                                                                                                                                                                                                                                                                              double r, R, alf, th, Bin, B0, Bsp;
                                                                                                                                                                                                                                                                                                                                               double x0, y0, z0, r2, om2, om, normr,dx,dy,dz;
                                                                                                                                                                                                                                                                                                                                                double Br, Bphi, Bth, ca, sa;
                                                                                                                                                                                                                                                                                                                                                 double Rr, Rr3, phi, ct, st, cphi, sphi, ar, ar2, ar3;
                                                                                                                                                                                                                                                                double prs,rho,vhc;
                                                                                                                                                                                                                                                                double isigma, normB, normP,emag0;                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                   x0=y0=z0=0.0;
                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                      r2 = D_EXPAND((x-x0)*(x-x0), + (y-y0)*(y-y0) , + (z-z0)*(z-z0));
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                dx = x - x0;
                                                                                                                                                                                                                                                                dy = y - y0;
                                                                                                                                                                                                                                                                dz = z - z0;
                                                                                                                                                                                                                                                                                                                                                       r = sqrt(r2)+1.e-115;
                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                         om2 = D_EXPAND((x-x0)*(x-x0), + (y-y0)*(y-y0) , + 0.0);
                                                                                                                                                                                                                                                                                                                                                          om = sqrt(om2);
                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                            R = g_inputParam[Rs];
                                                                                                                                                                                                                                                                                                                                                             Bsp = g_inputParam[B_per];
                                                                                                                                                                                                                                                                                                                                                              B0 = g_inputParam[B_POST];
                                                                                                                                                                                                                                                                
isigma = g_inputParam[Isig];     

vhc = g_inputParam[VH];
                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                alf = 4.49340945790906/R;
  
normB=sqrt(1.0/(1.0+isigma));   
normP=1.0-normB;                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                  Bin = -6.90501*B0;
                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                    ct = z/r;
                                                                                                                                                                                                                                                                                                                                                                     st = sqrt(1.-ct*ct);
                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                       phi  = atan2(y,x);
                                                                                                                                                                                                                                                                                                                                                                        sphi = sin(phi);
                                                                                                                                                                                                                                                                                                                                                                         cphi = cos(phi);
                                                                                                                                                                                                                                                                                                                                                                          normr = 1./(1.+0.*r2);                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                            if (r < R) {
                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                      ar = alf*r;
                                                                                                                                                                                                                                                                                                                                                                                          ar2 = ar*ar;
                                                                                                                                                                                                                                                                                                                                                                                              ar3 = ar2*ar;
                                                                                                                                                                                                                                                                                                                                                                                                  ca  = cos(ar);
                                                                                                                                                                                                                                                                                                                                                                                                      sa  = sin(ar);
                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                Br = -2.0*ct*(ar*ca-sa)*Bin/ar3;
                                                                                                                                                                                                                                                                                                                                                                                                                    Bth = -st*((ar2-1.0)*sa+ar*ca)*Bin/ar3;
                                                                                                                                                                                                                                                                                                                                                                                                                        Bphi = -st*(ar*ca-sa)*Bin/ar2;
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                prs = 1.0e-0*normr;
                                                                                                                                                                                                                                                                rho = 1.0e-0*normr;
                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                }else{
                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                          Rr = R/r;
                                                                                                                                                                                                                                                                                                                                                                                                                                              Rr3 = Rr*Rr*Rr;
                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                        Br = (1-Rr3)*ct*B0*Bsp;
                                                                                                                                                                                                                                                                                                                                                                                                                                                            Bth = -(1+0.5*Rr3)*st*B0*Bsp;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                Bphi = 0.0;
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                prs = normr/16.;
                                                                                                                                                                                                                                                                rho = normr/16;                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          

//normr = 1./(1.+0.*r2);                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          v[RHO] = rho;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              v[VX1] = dx*vhc;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                v[VX2] = dy*vhc;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  v[VX3] = dz*vhc;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      v[BX1] = normB*(Br*st*cphi + Bth*ct*cphi - Bphi*sphi);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        v[BX2] = normB*(Br*st*sphi + Bth*ct*sphi + Bphi*cphi) ;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          v[BX3] = normB*(Br*ct      - Bth*st);

 emag0 = 0.5*(Br*Br+Bth*Bth+Bphi*Bphi);                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              v[PRS] = prs+emag0*0.25*normP;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                /*  ----  CLOUD  ----  */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // r = D_EXPAND((x-x0)*(x-x0), + (y-y0)*(y-y0) , + (z-z0)*(z-z0));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // if (sqrt(r) < g_inputParam[RADIUS]) v[RHO] = 10.0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    /* no need for potential vector, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       since CT_VEC_POT_INIT is set to NO
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         v[AX1] = x3*v[BX2] - x2*v[BX3];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           v[AX2] = 0.0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             v[AX3] = 0.0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }

/* ********************************************************************* */
void InitDomain (Data *d, Grid *grid)
/*! 
 * Assign initial condition by looping over the computational domain.
 * Called after the usual Init() function to assign initial conditions
 * on primitive variables.
 * Value assigned here will overwrite those prescribed during Init().
 *
 *
 *********************************************************************** */
{
}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             /* ********************************************************************* */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             void Analysis (const Data *d, Grid *grid)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             /* 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                *********************************************************************** */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                { 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                /* ********************************************************************* */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                void UserDefBoundary (const Data *d, RBox *box, int side, Grid *grid) 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                /*
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  *********************************************************************** */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    int   i, j, k;
                                                                                                                                                                                                                                                                double rhofloor, prsfloor;
                                                                                                                                                                                                                                                                double vhc,vhct,rho0, prs0;
                                                                                                                                                                                                                                                                
double *x1;
double *x2;
double *x3;         

 x1 = grid[IDIR].x;
 x2 = grid[JDIR].x;
 x3 = grid[KDIR].x;

                                                                                                                                                                                                                                                                prsfloor = 1.0e-8;
                                                                                                                                                                                                                                                                rhofloor = 1.0e-8;
                                                                                                                                                                                                                                                                
vhc = g_inputParam[VH];           
vhct = vhc/(1.+vhc*g_time);
rho0 = 1./(16.*pow(1.+vhc*g_time,3));
prs0 = 1./(16.*pow(1.+vhc*g_time,4));
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                
 //if (side == 0) {    /* -- check solution inside domain -- */
    DOM_LOOP(k,j,i){
        
        if(d->Vc[RHO][k][j][i] < rhofloor) {
           // cout<<"rho("<<k<<","<<j<<","<<i<< ") = "<<d->Vc[RHO][k][j][i] ;
           // printf("  rho(%d,%d,%d) = %10.5e       %10.5e  %10.5e  %10.5e   \n ",k,j,i,d->Vc[RHO][k][j][i],  x1[i], x2[j], x3[k]);
            d->Vc[RHO][k][j][i] = rhofloor;
        }
        if(d->Vc[PRS][k][j][i] < prsfloor) {
           // printf("  prs(%d,%d,%d) = %10.5e         %10.5e  %10.5e  %10.5e   \n  ",k,j,i,d->Vc[PRS][k][j][i],  x1[i], x2[j], x3[k] );
            d->Vc[PRS][k][j][i] = prsfloor;
            //cout<<"PRS("<<k<<","<<j<<","<<i<< ") = "<<d->Vc[PRS][k][j][i] ;
        }
            //d->Vc[RHO][k][j][i] = MAX(  d->Vc[RHO][k][j][i] , 1.*rhofloor);
            //d->Vc[PRS][k][j][i]  = MAX(  d->Vc[PRS][k][j][i] , 1.*prsfloor);
    }                                                                                                                                                                                                                                                               
 //}                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (side == X1_BEG){          /* -- select the boundary side -- */
                                                                                                                                                                                                                                                                
       // printf("  rho(%d,%d,%d) = %10.5e       %10.5e  %10.5e  %10.5e   \n ",k,j,i,d->Vc[RHO][k][j][i],  x1[i], x2[j], x3[k]);                                                                                                                                                                                                                             
       BOX_LOOP(box,k,j,i){                                                                                                                                                                                                                                                         
           
           //r=sqrt(x1[i]*x1[i]+x2[j]*x2[j]+x3[k]*x3[k]);
           
           d->Vc[RHO][k][j][i] = MIN(rho0,d->Vc[RHO][k][j][i]);     
            d->Vc[PRS][k][j][i] = MIN(prs0,d->Vc[PRS][k][j][i]);
            d->Vc[VX1][k][j][i] = MIN(x1[i]*vhct,d->Vc[VX1][k][j][i]);
            d->Vc[VX2][k][j][i] = MIN(x2[j]*vhct,d->Vc[VX2][k][j][i]);
            d->Vc[VX3][k][j][i] = MIN(x3[k]*vhct,d->Vc[VX3][k][j][i]);
       }
                                                                                                                                                                                                                                                                }else if (side == X1_END){
                                                                                                                                                                                                                                                                
        BOX_LOOP(box,k,j,i){                                                                                                                                                                                                                                                         
           
           //r=sqrt(x1[i]*x1[i]+x2[j]*x2[j]+x3[k]*x3[k]);
           
            d->Vc[RHO][k][j][i] = MIN(rho0,d->Vc[RHO][k][j][i]);     
            d->Vc[PRS][k][j][i] = MIN(prs0,d->Vc[PRS][k][j][i]);
            d->Vc[VX1][k][j][i] = MAX(x1[i]*vhct,d->Vc[VX1][k][j][i]);
            d->Vc[VX2][k][j][i] = MAX(x2[j]*vhct,d->Vc[VX2][k][j][i]);
            d->Vc[VX3][k][j][i] = MAX(x3[k]*vhct,d->Vc[VX3][k][j][i]);
       }
                                                                                                                                                                                                                                                                }else if (side == X2_BEG){          /* -- select the boundary side -- */
       BOX_LOOP(box,k,j,i){                                                                                                                                                                                                                                                         
           
           //r=sqrt(x1[i]*x1[i]+x2[j]*x2[j]+x3[k]*x3[k]);
           
           d->Vc[RHO][k][j][i] = MIN(rho0,d->Vc[RHO][k][j][i]);     
            d->Vc[PRS][k][j][i] = MIN(prs0,d->Vc[PRS][k][j][i]);
            d->Vc[VX1][k][j][i] = MIN(x1[i]*vhct,d->Vc[VX1][k][j][i]);
            d->Vc[VX2][k][j][i] = MIN(x2[j]*vhct,d->Vc[VX2][k][j][i]);
            d->Vc[VX3][k][j][i] = MIN(x3[k]*vhct,d->Vc[VX3][k][j][i]);
       }
                                                                                                                                                                                                                                                                }else if (side == X2_END){
                                                                                                                                                                                                                                                                
        BOX_LOOP(box,k,j,i){                                                                                                                                                                                                                                                         
           
           //r=sqrt(x1[i]*x1[i]+x2[j]*x2[j]+x3[k]*x3[k]);
           
            d->Vc[RHO][k][j][i] = MIN(rho0,d->Vc[RHO][k][j][i]);     
            d->Vc[PRS][k][j][i] = MIN(prs0,d->Vc[PRS][k][j][i]);
            d->Vc[VX1][k][j][i] = MAX(x1[i]*vhct,d->Vc[VX1][k][j][i]);
            d->Vc[VX2][k][j][i] = MAX(x2[j]*vhct,d->Vc[VX2][k][j][i]);
            d->Vc[VX3][k][j][i] = MAX(x3[k]*vhct,d->Vc[VX3][k][j][i]);
       }
}else if (side == X3_BEG){          /* -- select the boundary side -- */
       BOX_LOOP(box,k,j,i){                                                                                                                                                                                                                                                         
           
           //r=sqrt(x1[i]*x1[i]+x2[j]*x2[j]+x3[k]*x3[k]);
           
           d->Vc[RHO][k][j][i] = MIN(rho0,d->Vc[RHO][k][j][i]);     
            d->Vc[PRS][k][j][i] = MIN(prs0,d->Vc[PRS][k][j][i]);
            d->Vc[VX1][k][j][i] = MIN(x1[i]*vhct,d->Vc[VX1][k][j][i]);
            d->Vc[VX2][k][j][i] = MIN(x2[j]*vhct,d->Vc[VX2][k][j][i]);
            d->Vc[VX3][k][j][i] = MIN(x3[k]*vhct,d->Vc[VX3][k][j][i]);
       }
                                                                                                                                                                                                                                                                }else if (side == X3_END){
                                                                                                                                                                                                                                                                
        BOX_LOOP(box,k,j,i){                                                                                                                                                                                                                                                         
           
           //r=sqrt(x1[i]*x1[i]+x2[j]*x2[j]+x3[k]*x3[k]);
           
            d->Vc[RHO][k][j][i] = MIN(rho0,d->Vc[RHO][k][j][i]);     
            d->Vc[PRS][k][j][i] = MIN(prs0,d->Vc[PRS][k][j][i]);
            d->Vc[VX1][k][j][i] = MAX(x1[i]*vhct,d->Vc[VX1][k][j][i]);
            d->Vc[VX2][k][j][i] = MAX(x2[j]*vhct,d->Vc[VX2][k][j][i]);
            d->Vc[VX3][k][j][i] = MAX(x3[k]*vhct,d->Vc[VX3][k][j][i]);
       }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                }
